events {
    worker_connections 1024;
}

pid /home/vova/sites/multi-domain.app/builds/nginx/nginx.pid;

http {
    error_log /home/vova/sites/multi-domain.app/builds/nginx/nginx-error.log debug;
    access_log /home/vova/sites/multi-domain.app/builds/nginx/nginx-access.log;
    include /etc/nginx/mime.types;
    
    # Определяем город по хосту
    map $host $city {
        city1.localhost "city1";
        city2.localhost "city2";
        default "city1";
    }
    
    server {
        listen 2222;
        server_name localhost city1.localhost city2.localhost;
        
        # ========== АНГЛИЙСКАЯ ВЕРСИЯ (/en/) ==========
        location /en/_nuxt/ {
            alias /home/vova/sites/multi-domain.app/builds/${city}-en/public/_nuxt/;
            try_files $uri =404;
        }
        
        location /en/_i18n/ {
            alias /home/vova/sites/multi-domain.app/builds/${city}-en/public/_i18n/;
            try_files $uri =404;
        }
        
        location /en/builds/ {
            alias /home/vova/sites/multi-domain.app/builds/${city}-en/public/builds/;
            try_files $uri =404;
        }
        
        location /en/ {
            alias /home/vova/sites/multi-domain.app/builds/${city}-en/public/;
            try_files $uri $uri/ /en/index.html;
        }
        
        # ========== РУССКАЯ ВЕРСИЯ (/) ==========
        location /_nuxt/ {
            root /home/vova/sites/multi-domain.app/builds/${city}-ru/public;
            try_files $uri =404;
        }
        
        location /_i18n/ {
            root /home/vova/sites/multi-domain.app/builds/${city}-ru/public;
            try_files $uri =404;
        }
        
        location /builds/ {
            root /home/vova/sites/multi-domain.app/builds/${city}-ru/public;
            try_files $uri =404;
        }
        
        location / {
            root /home/vova/sites/multi-domain.app/builds/${city}-ru/public;
            try_files $uri $uri/ /index.html;
        }
    }
}